### ISSUE TITLE
Solaris or Polaris?

### ISSUE THREAD

**Issue by micahlt** [NovaoTech/Solaris#38]
The repository name is different from the information in the README - what's the official name of this project?

**Comment by MikeDev101** [comment]
The project rebranded to Solaris. https://github.com/NovaoTech/Solaris/discussions/37

**Comment by micahlt** [comment]
Ah, didn't even think to check Discussions.  Thank you!

**Comment by VelocityDesign** [comment]
Yep, we're solaris now. I'm still working on rebranding repositories. I don't have a brand yet, so feel free to pitch in if you'd like :)

**Comment by micahlt** [comment]
I'll let you know if I think of anything - currently I'm super busy with school stuff, Itchy, Modchat, etc.

**Comment by VelocityDesign** [comment]
Understandable.
